version: '3'

services:
  # MySQL
  db:
    image: mysql:latest
    container_name: dolphin
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - database_network
    ports:
      - 3306:3306

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      PMA_HOST: db
    networks:
      - database_network

  backend:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - database_network

networks:
  database_network:


volumes:
  db_data:
