version: '3'

services:
  backend:
    build: ./backend
    # depends_on:
    #   - hjk-sql
    networks:
      - database_network
    container_name: backend-docker
    restart: always
    # env_file:
    #   - .env
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend-docker
    restart: always
    links:
      - backend

networks:
  database_network:
    external: true